version: '3'
services:
  db:
    image: postgres:10.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3307:3307"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  web:
    build: .
    command: >
      bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yorozuya
      - bundle:/yorozuya/vendor/bundle
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  bundle:
