default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: yorozuya_development
  host: db
  username: app_user_role
  password: password

test:
  <<: *default
  database: yorozuya_test
  host: db
  username: app_user_role
  password: password

# Herokuデプロイ時に再度見直す
production:
  <<: *default
  # database: db/production.sqlite3 変更
  database: yorozuya_production
  username: shoma
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %> # 追加